export const cameras = [
  {
    id: 1,
    name: "Camera 1",
    email: "sherwinwilliams@wobot.ai",
    health: { cloud: 75, disk: 75 },
    location: "New York City, NY",
    recorder: "New York Recorder",
    tasks: "3 Tasks",
    status: "Active",
    hasWarning: true,
  },
  {
    id: 2,
    name: "Camera 2",
    email: "sherwinwilliams@wobot.ai",
    health: { cloud: 65, disk: 60 },
    location: "New York City, NY",
    recorder: "New York Recorder",
    tasks: "5 Tasks",
    status: "Active",
    hasWarning: false,
  },
  {
    id: 3,
    name: "Camera 3",
    email: "OpenEye | H370-Dual Halo",
    health: { cloud: 68, disk: 0 },
    location: "Los Angeles, CA",
    recorder: "Los Angeles Recorder",
    tasks: "5 Tasks",
    status: "Active",
    hasWarning: false,
  },
  {
    id: 4,
    name: "Camera 4",
    email: "OpenEye | H370-Dual Halo",
    health: { cloud: 92, disk: 0 },
    location: "San Francisco, CA",
    recorder: "San Francisco Recorder",
    tasks: "N/A",
    status: "Inactive",
    hasWarning: false,
  },
  {
    id: 5,
    name: "Camera 5",
    email: "sherwinwilliams@wobot.ai",
    health: { cloud: 95, disk: 94 },
    location: "Chicago, IL",
    recorder: "N/A",
    tasks: "2 Tasks",
    status: "Active",
    hasWarning: false,
  },
  {
    id: 6,
    name: "Camera 6",
    email: "sherwinwilliams@wobot.ai",
    health: { cloud: 78, disk: 75 },
    location: "Miami, FL",
    recorder: "Miami Recorder",
    tasks: "N/A",
    status: "Active",
    hasWarning: false,
  },
  {
    id: 7,
    name: "Camera 7",
    email: "sherwinwilliams@wobot.ai",
    health: { cloud: 80, disk: 82 },
    location: "Miami, FL",
    recorder: "Miami Recorder",
    tasks: "2 Tasks",
    status: "Active",
    hasWarning: false,
  },
  {
    id: 8,
    name: "Camera 8",
    email: "OpenEye | H370-Dual Halo",
    health: { cloud: 0, disk: 78 },
    location: "Seattle, WA",
    recorder: "Seattle Recorder",
    tasks: "N/A",
    status: "Inactive",
    hasWarning: true,
  },
  {
    id: 9,
    name: "Camera 9",
    email: "sherwinwilliams@wobot.ai",
    health: { cloud: 85, disk: 82 },
    location: "San Diego, CA",
    recorder: "N/A",
    tasks: "4 Tasks",
    status: "Active",
    hasWarning: false,
  },
  {
    id: 10,
    name: "Camera 10",
    email: "sherwinwilliams@wobot.ai",
    health: { cloud: 88, disk: 85 },
    location: "Boston, MA",
    recorder: "N/A",
    tasks: "2 Tasks",
    status: "Active",
    hasWarning: false,
  },
];
